version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    
  server:
    build: ./server
    ports:
      - 4000:3000
    volumes:
      - ./server:/usr/src/backend-app
      - node_modules_b:/usr/src/backend-app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes:
  node_modules:
  node_modules_b:
  data:
  